// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
// Only import dotenv if available (not needed in production where env vars are set)
try {
  require("dotenv/config");
} catch (e) {
  // dotenv not available - that's fine, environment variables should be set directly
}

import { defineConfig, env } from "prisma/config";

// DATABASE_URL is only needed at runtime, not during prisma generate
// Use a placeholder during build if not set to avoid config errors
const databaseUrl = process.env.DATABASE_URL || "postgresql://placeholder:placeholder@localhost:5432/placeholder";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
